// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgkmbnnwyukyerqdqrco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBna21ibm53eXVreWVycWRxcmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTI4MjcsImV4cCI6MjA1OTU4ODgyN30.ZX6tMepxyd-qgMC5E-z1ITuDG4KVib_htkQCaMk7BUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);