// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkpfasuczaxmubkhsqth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcGZhc3VjemF4bXVia2hzcXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTY0OTgsImV4cCI6MjA2MjQ3MjQ5OH0.P3pS81YWMUHIWg1JnKonPpj_ibYnIMhKxd1hvHML6l0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
